[package]
name = "rating-icon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
anyhow = "1.0.79"
walkdir = "2.4.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# https://zenn.dev/dozo/articles/14b76b561f3b45
# Tell `rustc` to optimize for small code size.
opt-level = "s"
codegen-units = 1
lto = true
